### ISSUE TITLE
Difference to hadess/rtl8723bs

### ISSUE THREAD

**Issue by joerg-krause** [NextThingCo/RTL8723BS#5]
What are the differences between the firmware of the hadess repository (https://github.com/hadess/rtl8723bs) and the NTC one?

**Comment by V10lator** [comment]
These repositories contain drivers, not the firmware. Anyway, I would like to know the difference between the drivers, too.

And when we're already at it: hadess/rtl8723bs contains firmware (stored in https://github.com/hadess/rtl8723bs/blob/master/convert_firmware.h ) - What's the firmware this driver is using?

**Comment by joerg-krause** [comment]
Closed due to inactivity.
